language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master